---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  Role:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "s3.amazonaws.com"
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  Policy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "root"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action:
          - s3:Get**
          - s3:List**
          Resource:
          - "arn:aws:s3:::athoron-cf/hello/*"
          Effect: Allow
        - Action:
          - "logs:CreateLogGroup"
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Resource: "*"
          Effect: Allow
      Roles:
      - Ref: Role

  HelloMacroFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://athoron-cf/hello/src.zip
      Handler: index.handler
      Runtime: python3.6
      Timeout: 5

  Macro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: Hello
      FunctionName:
        Fn::GetAtt: [HelloMacroFunction, Arn]
